// Dados reais 2026 (De Bacco), linha a linha (25a rodada) - importados da
// planilha oficial de orcamento ("2026 - BUDGET DE BACCO", abas PLANEJADO
// 2026 e REALIZADO 2026), 1 lancamento por compra/mes (fornecedor, titulo
// da compra e quantidade quando a planilha informava). Substitui o dado
// agregado por categoria/mes da 24a rodada (ver
// utils/seedBudget2026DebaccoGranular.js).

const ENTRIES_2026_DEBACCO_GRANULAR = [
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 4000.0, realizado: 4000.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 4000.0, realizado: 4000.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 4000.0, realizado: 4000.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 4500.0, realizado: 4500.0, fornecedor: '', tituloCompra: 'Autodesk / 3D Maxx - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 70.0, realizado: 72.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 70.0, realizado: 72.37, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 70.0, realizado: 69.5, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 70.0, realizado: 71.98, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 70.0, realizado: 70.0, fornecedor: 'Shuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 19.99, realizado: 19.99, fornecedor: '', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 23500.0, realizado: null, fornecedor: 'Gráfica Imperial', tituloCompra: 'Catálogos (atualizados)', quantidade: 5000 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: null, realizado: 23500.0, fornecedor: 'Gráfica Imperial', tituloCompra: 'Catálogos (atualizados)', quantidade: 5000 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 25000.0, realizado: 25000.0, fornecedor: 'Gráfica Imperial', tituloCompra: 'Catálogos (atualizados)', quantidade: 5000 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: null, realizado: 653.97, fornecedor: '', tituloCompra: 'Ceicom- site', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 70.95, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 115.13, realizado: 115.13, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 135.0, realizado: 99.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 135.0, realizado: null, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: null, realizado: 800.0, fornecedor: '', tituloCompra: 'Corel Draw', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 1600.0, realizado: 1600.0, fornecedor: '', tituloCompra: 'Corona - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: null, realizado: 6998.5, fornecedor: '', tituloCompra: 'Desenvolvimento de Site - 2ª parcela', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: null, realizado: 3598.0, fornecedor: '', tituloCompra: 'E-commerce- De Bacco', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: null, realizado: 3598.0, fornecedor: '', tituloCompra: 'E-commerce- De Bacco', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 54.06, realizado: 52.43, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 65.0, realizado: 54.06, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 65.0, realizado: 52.29, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 65.0, realizado: 51.62, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 65.0, realizado: 50.51, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 65.0, realizado: 49.99, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 65.0, realizado: 49.99, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 49.99, realizado: 49.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: null, realizado: 1603.58, fornecedor: '', tituloCompra: 'Melissa- visitas á matriz', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 231.82, realizado: 231.82, fornecedor: '', tituloCompra: 'Motion Arr', quantidade: 'Ultimo pagamento' },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 100.0, realizado: null, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 100.0, realizado: 100.0, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 100.0, realizado: 100.0, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 100.0, realizado: 100.0, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 1250.0, realizado: null, fornecedor: '', tituloCompra: 'Poligoon (texturas) - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: null, realizado: 1149.0, fornecedor: '', tituloCompra: 'Poligoon (texturas) - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: null, realizado: 7466.04, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: null, realizado: 8859.83, fornecedor: '', tituloCompra: 'Promob', quantidade: null },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 11000.0, realizado: null, fornecedor: 'Casa Vip', tituloCompra: 'Revista Casa Vip - 1 pág. indet. (ímpar) - trimestral', quantidade: 3 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 11000.0, realizado: null, fornecedor: 'Casa Vip', tituloCompra: 'Revista Casa Vip - 1 pág. indet. (ímpar) - trimestral', quantidade: 3 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 11000.0, realizado: null, fornecedor: 'Casa Vip', tituloCompra: 'Revista Casa Vip - 1 pág. indet. (ímpar) - trimestral', quantidade: 3 },
  { category: 'Institucional - 2.5.3.3', month: 1, planejado: 127.45, realizado: null, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 127.45, realizado: 254.0, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 3, planejado: 127.45, realizado: 254.9, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 4, planejado: 127.45, realizado: 254.9, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 5, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 7, planejado: 127.45, realizado: 254.9, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 8, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 9, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 10, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 11, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 12, planejado: 127.45, realizado: 127.45, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.3.3', month: 6, planejado: 1300.0, realizado: 1300.0, fornecedor: '', tituloCompra: 'Sketchup - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.3.3', month: 2, planejado: 1646.5, realizado: 1646.5, fornecedor: '', tituloCompra: 'Uniformes (polo preta) - 50%', quantidade: 37 },
  { category: 'Relacionamento - 2.5.3.22', month: 7, planejado: 6000.0, realizado: 5000.0, fornecedor: 'Alex', tituloCompra: 'Alex - especificador interior de SP', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 6000.0, realizado: 5000.0, fornecedor: 'Alex', tituloCompra: 'Alex - especificador interior de SP', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 6000.0, realizado: 5000.0, fornecedor: 'Alex', tituloCompra: 'Alex - especificador interior de SP', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: 6000.0, realizado: 5000.0, fornecedor: 'Alex', tituloCompra: 'Alex - especificador interior de SP', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: 6000.0, realizado: 5000.0, fornecedor: 'Alex', tituloCompra: 'Alex - especificador interior de SP', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 12, planejado: 6000.0, realizado: 5000.0, fornecedor: 'Alex', tituloCompra: 'Alex - especificador interior de SP', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: null, realizado: 4000.0, fornecedor: '', tituloCompra: 'Arabesco- Glauber- Work shop do cliente', quantidade: null },
  { category: 'Relacionamento - 2.5.3.22', month: 5, planejado: null, realizado: 7500.0, fornecedor: '', tituloCompra: 'Bel Lar- Relacionamento com os 20 principais escritórios, ações ao longo do ano', quantidade: null },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: null, realizado: 3567.8, fornecedor: '', tituloCompra: 'Chá - eventos Refinare- Silvio', quantidade: 3 },
  { category: 'Relacionamento - 2.5.3.22', month: 1, planejado: 1850.0, realizado: null, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 2, planejado: 1850.0, realizado: null, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 3, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 5, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 6, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 7, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 12, planejado: 1850.0, realizado: 1850.0, fornecedor: 'Contour', tituloCompra: 'Contour Decor', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: null, realizado: 6500.0, fornecedor: '', tituloCompra: 'Conviva 26\\27- Viveza', quantidade: null },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: null, realizado: 1200.0, fornecedor: '', tituloCompra: 'Curso dI Bone- Mavine - Silvio', quantidade: null },
  { category: 'Relacionamento - 2.5.3.22', month: 1, planejado: 5000.0, realizado: null, fornecedor: 'Casoca', tituloCompra: 'Divulgação Casoca - Campanha Curadoria', quantidade: 1 },
  { category: 'Relacionamento - 2.5.3.22', month: 2, planejado: null, realizado: 3157.0, fornecedor: 'Casoca', tituloCompra: 'Divulgação Casoca - Campanha Curadoria', quantidade: 1 },
  { category: 'Relacionamento - 2.5.3.22', month: 3, planejado: null, realizado: 3157.0, fornecedor: 'Casoca', tituloCompra: 'Divulgação Casoca - Campanha Curadoria', quantidade: 1 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: null, realizado: 3157.0, fornecedor: 'Casoca', tituloCompra: 'Divulgação Casoca - Campanha Curadoria', quantidade: 1 },
  { category: 'Relacionamento - 2.5.3.22', month: 1, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 2, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 3, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 5, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 6, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 7, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 12, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'E-mail mkt - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 1, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 2, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 3, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 5, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 6, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 7, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 12, planejado: 970.0, realizado: 970.0, fornecedor: 'Casoca', tituloCompra: 'Hospedagem blocos 3D', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 25000.0, realizado: null, fornecedor: '', tituloCompra: 'I Simpósio De Bacco - O melhor da Cozinha', quantidade: null },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 25000.0, realizado: null, fornecedor: '', tituloCompra: 'I Simpósio De Bacco - O melhor da Cozinha', quantidade: null },
  { category: 'Relacionamento - 2.5.3.22', month: 1, planejado: 5000.0, realizado: null, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 2, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 3, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 5, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 6, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 7, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 12, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Arquitetando com Arte', tituloCompra: 'Luciane - especificadora Sul', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 1, planejado: 7500.0, realizado: null, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 2, planejado: 7500.0, realizado: 7500.0, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 3, planejado: 7500.0, realizado: 7500.0, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 4, planejado: 7500.0, realizado: 7500.0, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 5, planejado: 7500.0, realizado: 7500.0, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 6, planejado: 7500.0, realizado: 7500.0, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 7, planejado: 7500.0, realizado: 7500.0, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 8, planejado: 7500.0, realizado: null, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 9, planejado: 7500.0, realizado: null, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 10, planejado: 7500.0, realizado: null, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: 7500.0, realizado: null, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 12, planejado: 7500.0, realizado: null, fornecedor: 'Paula Leme.agência', tituloCompra: 'Paula Leme - consultora de relacionamento', quantidade: 12 },
  { category: 'Relacionamento - 2.5.3.22', month: 11, planejado: null, realizado: 15000.0, fornecedor: '', tituloCompra: 'Viveza- Palestra Divinopolis , 150 arq.', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 3, planejado: null, realizado: 228.5, fornecedor: '', tituloCompra: 'Bebidas evento contour - SIG 1984', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 2, planejado: null, realizado: 2423.0, fornecedor: '', tituloCompra: 'Buffet Peterson - Palestra Paula Leme (Vitória)', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 1440.0, fornecedor: '', tituloCompra: 'Buffet Peterson - Palestra Paula Leme (Vitória)', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 3, planejado: null, realizado: 2018.0, fornecedor: '', tituloCompra: 'Buffet- evento contour', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 2, planejado: null, realizado: 2423.0, fornecedor: '', tituloCompra: 'Evento M Gerais', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 4, planejado: null, realizado: 450.0, fornecedor: '', tituloCompra: 'Garçonete- evento contour', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 1, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Gastos hospedagem e alimentação Paula', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 3, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Gastos hospedagem e alimentação Paula', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 5, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Gastos hospedagem e alimentação Paula', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 7, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Gastos hospedagem e alimentação Paula', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 9, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Gastos hospedagem e alimentação Paula', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 11, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Gastos hospedagem e alimentação Paula', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 2, planejado: null, realizado: 2175.57, fornecedor: '', tituloCompra: 'Gastos passagem, hospedagem e alimentação Paula M Gerais', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 3, planejado: null, realizado: 396.83, fornecedor: '', tituloCompra: 'Gastos passagem, hospedagem e alimentação Paula M Gerais', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 3, planejado: null, realizado: 936.83, fornecedor: '', tituloCompra: 'Gastos Paula estimados', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 1296.6, fornecedor: '', tituloCompra: 'Gastos Paula estimados', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 8, planejado: null, realizado: 2329.41, fornecedor: '', tituloCompra: 'Gastos Paula estimados', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 9, planejado: null, realizado: 3000.0, fornecedor: '', tituloCompra: 'Gastos Paula estimados', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 11, planejado: null, realizado: 3000.0, fornecedor: '', tituloCompra: 'Gastos Paula estimados', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 2803.2, fornecedor: '', tituloCompra: 'Immersione- Paraiba- Silvio- Le Bagno', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 300.0, fornecedor: '', tituloCompra: 'Immersione- Paraiba- Silvio- Videomaker', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 787.6, fornecedor: 'Buffet', tituloCompra: 'Immersione- Recife- Silvio', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 1800.0, fornecedor: '', tituloCompra: 'Immersione- Showroom Escada- Silvio', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: null, realizado: 1600.0, fornecedor: '', tituloCompra: 'Immersione- Van- Silvio', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 1, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 2, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 3, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 4, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 5, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 6, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 7, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 8, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 9, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 10, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 11, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 12, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Immersiones em clientes', quantidade: 36 },
  { category: 'Immersiones - 2.5.3.2', month: 9, planejado: null, realizado: 15000.0, fornecedor: '', tituloCompra: 'Immersiones estimadas', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 10, planejado: null, realizado: 15000.0, fornecedor: '', tituloCompra: 'Immersiones estimadas', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 11, planejado: null, realizado: 15000.0, fornecedor: '', tituloCompra: 'Immersiones estimadas', quantidade: null },
  { category: 'Immersiones - 2.5.3.2', month: 12, planejado: null, realizado: 15000.0, fornecedor: '', tituloCompra: 'Immersiones estimadas', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 1, planejado: null, realizado: 8800.0, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 2, planejado: null, realizado: 9000.0, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 3, planejado: 5000.0, realizado: 9000.0, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 4, planejado: 5000.0, realizado: 9000.0, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 5, planejado: 5000.0, realizado: 9000.0, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 6, planejado: 5000.0, realizado: 9000.0, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 7, planejado: 5000.0, realizado: null, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 8, planejado: 5000.0, realizado: null, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 9, planejado: 5000.0, realizado: null, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 10, planejado: 5000.0, realizado: null, fornecedor: 'Amanda Ferber', tituloCompra: 'Influencer Amanda Ferber - lançamentos', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 6, planejado: null, realizado: 899.0, fornecedor: '', tituloCompra: 'Influencer Maiara', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 7, planejado: null, realizado: 899.0, fornecedor: '', tituloCompra: 'Influencer Maiara', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 8, planejado: null, realizado: 899.0, fornecedor: '', tituloCompra: 'Influencer Maiara', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 1, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 2, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 3, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 4, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 5, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 6, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 7, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 8, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 9, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 10, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 11, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 12, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 1, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 2, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 3, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 4, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 5, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 6, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 7, planejado: 15.0, realizado: 29.9, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 8, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 9, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 10, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 11, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 12, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 2, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 3, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 4, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 5, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 6, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 7, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 8, planejado: 2000.0, realizado: 1138.55, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 9, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 10, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 11, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 12, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 1, planejado: 2274.9, realizado: 2274.86, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 2, planejado: 800.0, realizado: 123.5, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 3, planejado: 800.0, realizado: 210.98, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 4, planejado: 800.0, realizado: 438.24, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 5, planejado: 800.0, realizado: 75.95, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 6, planejado: 800.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 7, planejado: 800.0, realizado: 698.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 8, planejado: 800.0, realizado: 623.95, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 9, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 10, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 11, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.3.5', month: 12, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 1, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 2, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 3, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 4, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 5, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 6, planejado: 500.0, realizado: 28.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 7, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 8, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 9, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 10, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 11, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 12, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 1, planejado: 350.0, realizado: null, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 2, planejado: 350.0, realizado: null, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 3, planejado: 350.0, realizado: 143.0, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 4, planejado: 350.0, realizado: 105.56, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 5, planejado: 350.0, realizado: 335.52, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 6, planejado: 350.0, realizado: null, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 7, planejado: 350.0, realizado: 128.0, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 8, planejado: 350.0, realizado: null, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 9, planejado: 350.0, realizado: 350.0, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 10, planejado: 350.0, realizado: 350.0, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 11, planejado: 350.0, realizado: 350.0, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 12, planejado: 350.0, realizado: 350.0, fornecedor: '', tituloCompra: 'Ingredientes para receitas', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 2, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tampos', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 5, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tampos', quantidade: null },
  { category: 'Cenografia - 2.5.3.6', month: 9, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tampos', quantidade: null },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 12480.0, realizado: 12480.0, fornecedor: '', tituloCompra: 'Avental', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 8, planejado: 14000.0, realizado: null, fornecedor: '', tituloCompra: 'Avental', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 9, planejado: null, realizado: 14000.0, fornecedor: '', tituloCompra: 'Avental', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 5180.0, realizado: null, fornecedor: '', tituloCompra: 'Caixa para copos de café', quantidade: '400 / 200' },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: null, realizado: 5180.0, fornecedor: '', tituloCompra: 'Caixa para copos de café', quantidade: '400 / 200' },
  { category: 'Brindes - 2.5.3.8', month: 6, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Caixa unitária para copos', quantidade: 1000 },
  { category: 'Brindes - 2.5.3.8', month: 9, planejado: null, realizado: 5000.0, fornecedor: '', tituloCompra: 'Caixa unitária para copos', quantidade: 1000 },
  { category: 'Brindes - 2.5.3.8', month: 5, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Caneta Metalica', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 9, planejado: null, realizado: 3000.0, fornecedor: '', tituloCompra: 'Caneta Metalica', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 14000.0, realizado: null, fornecedor: 'Importado', tituloCompra: 'Copinhos café', quantidade: 1000 },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: null, realizado: 14000.0, fornecedor: 'Importado', tituloCompra: 'Copinhos café', quantidade: 1000 },
  { category: 'Brindes - 2.5.3.8', month: 6, planejado: 15000.0, realizado: null, fornecedor: 'Importado', tituloCompra: 'Copinhos café', quantidade: 1000 },
  { category: 'Brindes - 2.5.3.8', month: 9, planejado: null, realizado: 15000.0, fornecedor: 'Importado', tituloCompra: 'Copinhos café', quantidade: 1000 },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 5250.0, realizado: null, fornecedor: 'Sulcel', tituloCompra: 'Luva', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: null, realizado: 5250.0, fornecedor: 'Sulcel', tituloCompra: 'Luva', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 8, planejado: 5500.0, realizado: null, fornecedor: 'Sulcel', tituloCompra: 'Luva', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 9, planejado: null, realizado: 5500.0, fornecedor: 'Sulcel', tituloCompra: 'Luva', quantidade: 500 },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 9375.0, realizado: null, fornecedor: '', tituloCompra: 'Lápis Preto 2B Swarovski', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: 9375.0, realizado: 9375.0, fornecedor: '', tituloCompra: 'Lápis Preto 2B Swarovski', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 3, planejado: null, realizado: 9375.0, fornecedor: '', tituloCompra: 'Lápis Preto 2B Swarovski', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 10, planejado: 19000.0, realizado: 19000.0, fornecedor: '', tituloCompra: 'Lápis Preto 2B Swarovski', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 13583.0, realizado: 42250.0, fornecedor: 'Kaygangue', tituloCompra: 'Prancheta', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: 13583.0, realizado: null, fornecedor: 'Kaygangue', tituloCompra: 'Prancheta', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 3, planejado: 13583.0, realizado: null, fornecedor: 'Kaygangue', tituloCompra: 'Prancheta', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 10, planejado: 41000.0, realizado: 41000.0, fornecedor: 'Kaygangue', tituloCompra: 'Prancheta', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 11, planejado: 7500.0, realizado: 7500.0, fornecedor: '', tituloCompra: 'Presente especial novo cliente', quantidade: null },
  { category: 'Brindes - 2.5.3.8', month: 12, planejado: 7500.0, realizado: 7500.0, fornecedor: '', tituloCompra: 'Presente especial novo cliente', quantidade: null },
  { category: 'Brindes - 2.5.3.8', month: 3, planejado: null, realizado: 25.0, fornecedor: '', tituloCompra: 'Recepção Paula Leme- SIG 1957', quantidade: 1 },
  { category: 'Brindes - 2.5.3.8', month: 1, planejado: 4240.0, realizado: null, fornecedor: '', tituloCompra: 'Saca Rolha Manual', quantidade: 400 },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: null, realizado: 4240.0, fornecedor: '', tituloCompra: 'Saca Rolha Manual', quantidade: 400 },
  { category: 'Brindes - 2.5.3.8', month: 8, planejado: 4500.0, realizado: null, fornecedor: '', tituloCompra: 'Saca Rolha Manual', quantidade: 400 },
  { category: 'Brindes - 2.5.3.8', month: 9, planejado: null, realizado: 4000.0, fornecedor: '', tituloCompra: 'Saca Rolha Manual', quantidade: 400 },
  { category: 'Brindes - 2.5.3.8', month: 2, planejado: 12000.0, realizado: 9150.0, fornecedor: '', tituloCompra: 'Sacolas', quantidade: 5000 },
  { category: 'Brindes - 2.5.3.8', month: 10, planejado: 12000.0, realizado: 12000.0, fornecedor: '', tituloCompra: 'Sacolas', quantidade: 5000 },
  { category: 'PDV - 2.5.3.12', month: 1, planejado: 51.3, realizado: null, fornecedor: 'Mubisys', tituloCompra: 'Logo (Flávio Bacana)', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 2, planejado: null, realizado: 51.3, fornecedor: 'Mubisys', tituloCompra: 'Logo (Flávio Bacana)', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 5, planejado: null, realizado: 550.0, fornecedor: '', tituloCompra: 'Logo - SIG 2195', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 4, planejado: null, realizado: 200.0, fornecedor: '', tituloCompra: 'Logos representante (Flávi Bacana) SOLI 1688', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 1, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 2, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 3, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 4, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 5, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 6, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 7, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 8, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 9, planejado: 1500.0, realizado: 1500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 10, planejado: 1500.0, realizado: 1500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 11, planejado: 1500.0, realizado: 1500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 12, planejado: 1500.0, realizado: 1500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'PDV - 2.5.3.12', month: 4, planejado: null, realizado: 370.0, fornecedor: '', tituloCompra: 'PLacas de acrílico- SIG 2059', quantidade: 10 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 15869.99, fornecedor: '', tituloCompra: 'Acerto de Viagem - alimentação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 7709.29, fornecedor: '', tituloCompra: 'Acerto de Viagem - Carros', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 866.64, fornecedor: '', tituloCompra: 'Acerto de viagem- outros', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 90.0, fornecedor: 'Garage', tituloCompra: 'Adesivos Capacete', quantidade: '60 UN' },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 1806.63, fornecedor: '', tituloCompra: 'Arq&Decor - espaço', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 1806.63, fornecedor: '', tituloCompra: 'Arq&Decor - espaço', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 4, planejado: null, realizado: 1806.63, fornecedor: '', tituloCompra: 'Arq&Decor - espaço', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 5, planejado: null, realizado: 1806.63, fornecedor: '', tituloCompra: 'Arq&Decor - espaço', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 6, planejado: 10000.0, realizado: 1806.63, fornecedor: '', tituloCompra: 'Arq&Decor - espaço', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 6, planejado: 8000.0, realizado: 64052.68, fornecedor: '', tituloCompra: 'Arq&Decor - stand + ações', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 6, planejado: null, realizado: 9120.0, fornecedor: 'cliente Studio Kitchen', tituloCompra: 'Casa Cor - MT', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 7, planejado: null, realizado: 2800.0, fornecedor: 'Mais design', tituloCompra: 'Casa Cor ES - ações', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 6, planejado: null, realizado: 5180.0, fornecedor: 'cliente MGerais', tituloCompra: 'Casa Cor ES - cota bronze', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 6, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Casa Cor MT - ações', quantidade: 2 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 7, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Casa Cor MT - ações', quantidade: 2 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 5, planejado: 10000.0, realizado: null, fornecedor: '', tituloCompra: 'Casa Cor MT - cota bronze', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 8, planejado: null, realizado: 4400.0, fornecedor: '', tituloCompra: 'Casa Cor MT- Ações', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 9, planejado: null, realizado: 5000.0, fornecedor: '', tituloCompra: 'Casa Cor MT- Ações', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 9, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Casa Cor Ribeirão Preto - SP - ações', quantidade: 2 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 10, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Casa Cor Ribeirão Preto - SP - ações', quantidade: 2 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 8, planejado: 10000.0, realizado: null, fornecedor: '', tituloCompra: 'Casa Cor Ribeirão Preto - SP - espaço', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 15555.0, fornecedor: 'Anfacer', tituloCompra: 'ExooRevestir KVA Básico', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 5429.0, fornecedor: 'Zassi', tituloCompra: 'ExpoRevestir - Camisa', quantidade: '50+7' },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: 5429.0, realizado: 940.0, fornecedor: 'Zassi', tituloCompra: 'ExpoRevestir - Camisa', quantidade: '50+7' },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: 1400.0, realizado: null, fornecedor: 'DLamb', tituloCompra: 'ExpoRevestir - Camisa Staff', quantidade: 23 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 759.0, fornecedor: 'DLamb', tituloCompra: 'ExpoRevestir - Camisa Staff', quantidade: 23 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 3156.66, fornecedor: 'Casoca', tituloCompra: 'ExpoRevestir - Casoca', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 3156.66, fornecedor: 'Casoca', tituloCompra: 'ExpoRevestir - Casoca', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: 420.0, realizado: 420.0, fornecedor: 'Primeset', tituloCompra: 'ExpoRevestir - Cordões', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: 25941.66, realizado: 25941.66, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir - Espaço', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: 25941.66, realizado: 25941.66, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir - Espaço', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: 450.0, realizado: null, fornecedor: 'Garage', tituloCompra: 'ExpoRevestir - Placas de Identificação em acrilico', quantidade: 174 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 825.0, fornecedor: 'Garage', tituloCompra: 'ExpoRevestir - Placas de Identificação em acrilico', quantidade: 174 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: 44000.0, realizado: 44000.0, fornecedor: 'ArqEventos', tituloCompra: 'ExpoRevestir - Stand', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: 44000.0, realizado: 44000.0, fornecedor: 'ArqEventos', tituloCompra: 'ExpoRevestir - Stand', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: 44000.0, realizado: 44000.0, fornecedor: 'ArqEventos', tituloCompra: 'ExpoRevestir - Stand', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 4, planejado: 44000.0, realizado: 44000.0, fornecedor: 'ArqEventos', tituloCompra: 'ExpoRevestir - Stand', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 5, planejado: null, realizado: 14286.17, fornecedor: 'ArqEventos', tituloCompra: 'ExpoRevestir - Stand Extras', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: 3749.25, realizado: 3749.25, fornecedor: 'Inout', tituloCompra: 'ExpoRevestir - Vídeo e Fotos', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: 3749.25, realizado: 3749.25, fornecedor: 'Inout', tituloCompra: 'ExpoRevestir - Vídeo e Fotos', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 5, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 6, planejado: 15000.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 7, planejado: 15000.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 8, planejado: 15000.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 9, planejado: 15000.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 10, planejado: 15000.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 11, planejado: 26800.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 26800.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Espaço 100m / 150m - Locação', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 11, planejado: 46200.0, realizado: 46200.0, fornecedor: 'Arq Eventos', tituloCompra: 'ExpoRevestir 2027 - Espaço 150m - Montagem', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 46200.0, realizado: 46200.0, fornecedor: 'Arq Eventos', tituloCompra: 'ExpoRevestir 2027 - Espaço 150m - Montagem', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 2090.0, realizado: 2090.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas (hidraulica extra)', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 21800.0, realizado: 21800.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas (KVA\'s extra)', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 1050.0, realizado: 1050.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas Obrigatórias (extintores)', quantidade: 4 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 1460.0, realizado: 1460.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas Obrigatórias (hidraulica)', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 16400.0, realizado: 16400.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas Obrigatórias (KVA\'s Básico)', quantidade: 15 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 1079.4, realizado: 1079.4, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas Obrigatórias (seguro)', quantidade: '1 - cota prata' },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 12, planejado: 385.0, realizado: 385.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027 - Taxas Obrigatórias (taxa municipal)', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 11, planejado: 135.0, realizado: 135.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027- RRT', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 11, planejado: 750.0, realizado: 750.0, fornecedor: '', tituloCompra: 'ExpoRevestir 2027- RRT UNT', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 7650.0, fornecedor: '', tituloCompra: 'ExpoRevestir Buffet', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: 11250.0, realizado: 10350.0, fornecedor: '', tituloCompra: 'ExpoRevestir Buffet', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 8150.0, fornecedor: '', tituloCompra: 'ExpoRevestir Café', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 8150.0, fornecedor: '', tituloCompra: 'ExpoRevestir Café', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 2150.0, fornecedor: '', tituloCompra: 'ExpoRevestir Coletor de Dados', quantidade: 1 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 647.56, fornecedor: '', tituloCompra: 'ExpoRevestir Credencial segurança', quantidade: '7dias' },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 1019.71, fornecedor: '', tituloCompra: 'ExpoRevestir Decoração', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: 2.0, realizado: 991.06, fornecedor: 'Zassi', tituloCompra: 'ExpoRevestir extintores', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 15687.0, fornecedor: 'Transamerica', tituloCompra: 'ExpoRevestir Hotel', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 40582.5, fornecedor: 'Transamerica', tituloCompra: 'ExpoRevestir Hotel', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 4, planejado: 45000.0, realizado: null, fornecedor: 'Transamerica', tituloCompra: 'ExpoRevestir Hotel', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 2061.75, fornecedor: '', tituloCompra: 'ExpoRevestir Infuencer Melina', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 4, planejado: null, realizado: 613.85, fornecedor: '', tituloCompra: 'ExpoRevestir Infuencer Melina', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 20740.0, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir KVA Extra', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 2300.0, fornecedor: '', tituloCompra: 'ExpoRevestir Letreiro Extra', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 1200.0, fornecedor: '', tituloCompra: 'ExpoRevestir limpeza', quantidade: '8 dias' },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 49.9, fornecedor: 'Camila Flores', tituloCompra: 'ExpoRevestir Pedras decorativas', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 1893.89, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir Ponto Extra hidráulico', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 1358.38, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir Ponto hidráulico', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 125.4, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir RRT', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 707.52, fornecedor: 'UNT', tituloCompra: 'ExpoRevestir RRT UNT', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 647.56, fornecedor: '', tituloCompra: 'ExpoRevestir segurança', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 1028.0, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir Seguro', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: null, realizado: 10350.0, fornecedor: '', tituloCompra: 'ExpoRevestir Taxa facilities', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 366.0, fornecedor: 'Anfacer', tituloCompra: 'ExpoRevestir Taxa Municipal', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 1, planejado: null, realizado: 700.0, fornecedor: 'Nuernberg', tituloCompra: 'ExpoRevestir Taxas Extras na Feira', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 650.92, fornecedor: '', tituloCompra: 'ExpoRevestir- despesas assessoria', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 11, planejado: 10870.0, realizado: 10870.0, fornecedor: '', tituloCompra: 'ExpoRevetir 2027- Taxas Obrigatórias (facilities)', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 2, planejado: 7500.0, realizado: 4920.0, fornecedor: '', tituloCompra: 'Folder lançamentos', quantidade: 3000 },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 5, planejado: 60000.0, realizado: null, fornecedor: '', tituloCompra: 'InduMóveis', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 9, planejado: null, realizado: 5000.0, fornecedor: 'cliente Coifas Gourmet', tituloCompra: 'Mostra Morar Bem - Presidente Prudente', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 3, planejado: null, realizado: 13279.84, fornecedor: '', tituloCompra: 'Passagem', quantidade: null },
  { category: 'Feiras/Eventos - 2.5.3.1', month: 7, planejado: null, realizado: 400.0, fornecedor: 'Cliente Refinare e Mavinee', tituloCompra: 'Videomaker para Mostra Rio Mar Casa- PB', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 5, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 6, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 7, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 8, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 9, planejado: 7000.0, realizado: 7000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 10, planejado: 7000.0, realizado: 7000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 11, planejado: 7000.0, realizado: 14000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 12, planejado: 7000.0, realizado: 14000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 8, planejado: null, realizado: 2025.0, fornecedor: '', tituloCompra: 'Showroom - SP (materiais)', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 5, planejado: null, realizado: 2900.0, fornecedor: '', tituloCompra: 'Showroom Escada - elétrica', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 8, planejado: null, realizado: 1000.0, fornecedor: '', tituloCompra: 'Showroom- SP (serviço)', quantidade: null },
  { category: 'Showroom - 2.5.3.13', month: 9, planejado: null, realizado: 2000.0, fornecedor: '', tituloCompra: 'Showroom- SP (serviço)', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 4, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 5, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 6, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 7, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 8, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 9, planejado: 5000.0, realizado: 5000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 10, planejado: 5000.0, realizado: 5000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 11, planejado: 5000.0, realizado: 5000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.3.14', month: 12, planejado: 5000.0, realizado: 20000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 4, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 5, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 6, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 7, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 8, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 9, planejado: 9500.0, realizado: 9500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 10, planejado: 9500.0, realizado: 9500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 11, planejado: 9500.0, realizado: 19000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 12, planejado: 9500.0, realizado: 9500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 8, planejado: null, realizado: 26280.0, fornecedor: '', tituloCompra: 'Showroom Refinare Boa Viagem - Silvio', quantidade: null },
  { category: 'Expositores Especiais - 2.5.3.21', month: 7, planejado: null, realizado: 10000.0, fornecedor: '', tituloCompra: 'Viveza - Loja Varginha', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 1, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 2, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 3, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 4, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 5, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 6, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 7, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 8, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 9, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 10, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 11, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Equipamentos - 1.2.6.1', month: 12, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
];

module.exports = { ENTRIES_2026_DEBACCO_GRANULAR };
