// Dados reais 2026 (GhelPlus), linha a linha (25a rodada) - importados da
// planilha oficial de orcamento ("2026- BUDGET GHELPLUS.xlsx", abas
// PLANEJADO 2026 e REALIZADO 2026), 1 lancamento por compra/mes (fornecedor,
// titulo da compra e quantidade quando a planilha informava). Substitui o
// dado agregado por categoria/mes da 23a rodada (ver
// utils/seedBudget2026GhelplusGranular.js).

const ENTRIES_2026_GHELPLUS_GRANULAR = [
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 3750.0, realizado: 3750.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 4000.0, realizado: 4000.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 4000.0, realizado: 4000.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 4000.0, realizado: 4000.0, fornecedor: 'UNT', tituloCompra: 'Agência de design - 50%', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: null, realizado: 2500.0, fornecedor: '', tituloCompra: 'Assessor Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: null, realizado: 2500.0, fornecedor: '', tituloCompra: 'Assessor Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: null, realizado: 5000.0, fornecedor: '', tituloCompra: 'Assessor Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: null, realizado: 5000.0, fornecedor: '', tituloCompra: 'Assessor Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: null, realizado: 5000.0, fornecedor: '', tituloCompra: 'Assessor Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 4186.61, realizado: 4186.61, fornecedor: 'Denise Delalamo', tituloCompra: 'Assessoria de Imprensa + clipping - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 4500.0, realizado: 4500.0, fornecedor: '', tituloCompra: 'Autodesk / 3D Maxx - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 70.0, realizado: 72.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 70.0, realizado: 72.37, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 70.0, realizado: 69.5, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 70.0, realizado: 71.98, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 70.0, realizado: 70.32, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 70.0, realizado: 70.0, fornecedor: 'Shtuterstock', tituloCompra: 'Banco de Imagens - 50% (US$ 25,06)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 29.0, realizado: 29.0, fornecedor: '', tituloCompra: 'Canva - 50%', quantidade: '(anual)' },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 19.99, realizado: null, fornecedor: 'CANCELADO', tituloCompra: 'Capcut - 50%', quantidade: '(valor anual)' },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: null, realizado: 8000.0, fornecedor: '', tituloCompra: 'Catálogos', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 20000.0, realizado: null, fornecedor: '', tituloCompra: 'Catálogos', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: null, realizado: 8000.0, fornecedor: '', tituloCompra: 'Catálogos', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 20000.0, realizado: null, fornecedor: '', tituloCompra: 'Catálogos', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: null, realizado: 8000.0, fornecedor: '', tituloCompra: 'Catálogos', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 70.95, realizado: 70.95, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 20.0, realizado: 70.95, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 20.0, realizado: 70.95, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 20.0, realizado: 70.95, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 20.0, realizado: null, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 20.0, realizado: null, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 20.0, realizado: 70.95, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 20.0, realizado: 70.83, fornecedor: '', tituloCompra: 'CG Mood (biblioteca 3D) - 50% (6.00€)', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 135.0, realizado: 135.0, fornecedor: 'Open IA', tituloCompra: 'Chat GPT', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: null, realizado: 800.0, fornecedor: '', tituloCompra: 'Corel Draw', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 1600.0, realizado: 1600.0, fornecedor: '', tituloCompra: 'Corona - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 8000.0, realizado: null, fornecedor: '', tituloCompra: 'Folder', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 8000.0, realizado: null, fornecedor: '', tituloCompra: 'Folder', quantidade: 4000 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 54.06, realizado: 52.43, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 65.0, realizado: 54.06, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 65.0, realizado: 52.29, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 65.0, realizado: 51.62, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 65.0, realizado: null, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 65.0, realizado: null, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 65.0, realizado: 50.51, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 65.0, realizado: 49.99, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 65.0, realizado: 65.0, fornecedor: '', tituloCompra: 'Freepik - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 96.99, realizado: 96.99, fornecedor: '', tituloCompra: 'Google One', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 10.0, realizado: 10.0, fornecedor: '', tituloCompra: 'Hostgator - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 53.9, realizado: null, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 53.9, realizado: 53.9, fornecedor: '', tituloCompra: 'Icloud - 50%', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 897.0, realizado: 897.0, fornecedor: 'Inout', tituloCompra: 'Manutenção site - 5h/mês', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: null, realizado: 800.0, fornecedor: '', tituloCompra: 'Maquiagem- Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: null, realizado: 1603.58, fornecedor: 'Hotel', tituloCompra: 'Melissa- visitas á matriz', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: null, realizado: 10000.0, fornecedor: '', tituloCompra: 'Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: null, realizado: 10000.0, fornecedor: '', tituloCompra: 'Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: null, realizado: 20000.0, fornecedor: '', tituloCompra: 'Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: null, realizado: 20000.0, fornecedor: '', tituloCompra: 'Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: null, realizado: 20000.0, fornecedor: '', tituloCompra: 'Milene Domingues', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 25000.0, realizado: null, fornecedor: 'Rádio Craque Neto', tituloCompra: 'Mídia - Rádio Craque Neto', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 25000.0, realizado: null, fornecedor: 'Rádio Craque Neto', tituloCompra: 'Mídia - Rádio Craque Neto', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 25000.0, realizado: null, fornecedor: 'Rádio Craque Neto', tituloCompra: 'Mídia - Rádio Craque Neto', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 25000.0, realizado: null, fornecedor: 'Rádio Craque Neto', tituloCompra: 'Mídia - Rádio Craque Neto', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 100.0, realizado: null, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 100.0, realizado: 100.0, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 100.0, realizado: 100.0, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 100.0, realizado: 100.0, fornecedor: '', tituloCompra: 'Offs Brasil - locuções grátis - 50%', quantidade: 'créditos' },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: null, realizado: 1375.0, fornecedor: '', tituloCompra: 'Patrocinio Feira de Ampére', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: null, realizado: 1375.0, fornecedor: '', tituloCompra: 'Patrocinio Feira de Ampére', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: null, realizado: 1375.0, fornecedor: '', tituloCompra: 'Patrocinio Feira de Ampére', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: null, realizado: 1375.0, fornecedor: '', tituloCompra: 'Patrocinio Feira de Ampére', quantidade: null },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 1250.0, realizado: null, fornecedor: '', tituloCompra: 'Poligoon (texturas) - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: null, realizado: 1149.0, fornecedor: '', tituloCompra: 'Poligoon (texturas) - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.2.3', month: 1, planejado: 181.35, realizado: null, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 181.35, realizado: 109.0, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: 181.35, realizado: null, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 4, planejado: 181.35, realizado: 109.0, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 5, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 7, planejado: 181.35, realizado: 53.9, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 8, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 9, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 10, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 11, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 12, planejado: 181.35, realizado: 181.35, fornecedor: 'Meta', tituloCompra: 'Selo de Verificação', quantidade: 12 },
  { category: 'Institucional - 2.5.2.3', month: 6, planejado: 1300.0, realizado: 1300.0, fornecedor: '', tituloCompra: 'Sketchup - 50%', quantidade: '1 (anual)' },
  { category: 'Institucional - 2.5.2.3', month: 2, planejado: 1646.5, realizado: 1646.5, fornecedor: '', tituloCompra: 'Uniformes (polo preta) - 50%', quantidade: 37 },
  { category: 'Institucional - 2.5.2.3', month: 3, planejado: null, realizado: 756.0, fornecedor: '', tituloCompra: 'Uniformes Extra', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 7, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'APAE - almoço beneficente', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 1, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 2, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 3, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 4, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 5, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 6, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 7, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 8, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 9, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 10, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 11, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 12, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 3, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Rejuntar', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 6, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Rejuntar', quantidade: null },
  { category: 'Ações Sociais - 2.5.2.4', month: 9, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Rejuntar', quantidade: null },
  { category: 'Relacionamento - 2.5.2.21', month: 1, planejado: 436.62, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 2, planejado: 436.61, realizado: 436.62, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 3, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 4, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 5, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 6, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 7, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 8, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 9, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 10, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 11, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Relacionamento - 2.5.2.21', month: 12, planejado: 436.61, realizado: 436.61, fornecedor: 'Ramper', tituloCompra: 'Ramper - 50%', quantidade: 12 },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: null, realizado: 90.27, fornecedor: '', tituloCompra: 'Easy whatsapp', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 6, planejado: null, realizado: 400.01, fornecedor: '', tituloCompra: 'Easy whatsapp', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: null, realizado: 1750.0, fornecedor: 'Inout', tituloCompra: 'Gravação no CD- Milene', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 1, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 2, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 3, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 6, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 7, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 8, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 9, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 10, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 11, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 12, planejado: 5000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 7, planejado: null, realizado: 3500.0, fornecedor: '', tituloCompra: 'Influencers Braun pedreiro', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 8, planejado: null, realizado: 3500.0, fornecedor: '', tituloCompra: 'Influencers Braun pedreiro', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 9, planejado: null, realizado: 7000.0, fornecedor: '', tituloCompra: 'Influencers Braun pedreiro', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 10, planejado: null, realizado: 7000.0, fornecedor: '', tituloCompra: 'Influencers Braun pedreiro', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 11, planejado: null, realizado: 7000.0, fornecedor: '', tituloCompra: 'Influencers Braun pedreiro', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 12, planejado: null, realizado: 7000.0, fornecedor: '', tituloCompra: 'Influencers Braun pedreiro', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 1, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 2, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 3, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 4, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 6, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 7, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 8, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 9, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 10, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 11, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 12, planejado: 6.95, realizado: 6.95, fornecedor: '', tituloCompra: 'Link Bio - árvore de links para cartão digital - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 1, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 2, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 3, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 4, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 6, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 7, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 8, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 9, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 10, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 11, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 12, planejado: 15.0, realizado: 15.0, fornecedor: '', tituloCompra: 'QR CODE FÁCIL - 50%', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 1, planejado: 425.84, realizado: 425.84, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 2, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 3, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 4, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 6, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 7, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 8, planejado: 2000.0, realizado: 1331.05, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 9, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 10, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 11, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 12, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Google', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 1, planejado: 1143.93, realizado: 1215.99, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 2, planejado: 800.0, realizado: 331.39, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 3, planejado: 800.0, realizado: 87.98, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 4, planejado: 800.0, realizado: 206.98, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 5, planejado: 800.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 6, planejado: 800.0, realizado: 749.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 7, planejado: 800.0, realizado: null, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 8, planejado: 800.0, realizado: 763.95, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 9, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 10, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 11, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Redes Sociais - 2.5.2.5', month: 12, planejado: 800.0, realizado: 800.0, fornecedor: '', tituloCompra: 'Tráfego Pago - Meta', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 1, planejado: 28.0, realizado: 28.0, fornecedor: '', tituloCompra: 'Barba para vídeo de Natal', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 1, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 2, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 3, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 4, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 5, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 6, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 7, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 8, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 9, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 10, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 11, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 12, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Decoração', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 2, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tampos', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 5, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Tampos', quantidade: null },
  { category: 'Cenografia - 2.5.2.6', month: 9, planejado: 2000.0, realizado: 2000.0, fornecedor: '', tituloCompra: 'Tampos', quantidade: null },
  { category: 'Brindes - 2.5.2.8', month: 4, planejado: null, realizado: 300.0, fornecedor: '', tituloCompra: 'Adesivo para o sal', quantidade: 400 },
  { category: 'Brindes - 2.5.2.8', month: 3, planejado: null, realizado: 9000.0, fornecedor: 'Kaygangue (SIG 1776)', tituloCompra: 'Bloco rascunho', quantidade: 3000 },
  { category: 'Brindes - 2.5.2.8', month: 5, planejado: 9000.0, realizado: null, fornecedor: 'Kaygangue (SIG 1776)', tituloCompra: 'Bloco rascunho', quantidade: 3000 },
  { category: 'Brindes - 2.5.2.8', month: 8, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Boné', quantidade: 1000 },
  { category: 'Brindes - 2.5.2.8', month: 9, planejado: null, realizado: 15000.0, fornecedor: '', tituloCompra: 'Boné', quantidade: 1000 },
  { category: 'Brindes - 2.5.2.8', month: 10, planejado: 9200.0, realizado: 9200.0, fornecedor: '', tituloCompra: 'Calendário', quantidade: 3000 },
  { category: 'Brindes - 2.5.2.8', month: 1, planejado: 2875.0, realizado: null, fornecedor: 'Junior Brindes', tituloCompra: 'Caneta metálica', quantidade: 500 },
  { category: 'Brindes - 2.5.2.8', month: 2, planejado: null, realizado: 2875.0, fornecedor: 'Junior Brindes', tituloCompra: 'Caneta metálica', quantidade: 500 },
  { category: 'Brindes - 2.5.2.8', month: 9, planejado: 2875.0, realizado: 2925.0, fornecedor: 'Junior Brindes', tituloCompra: 'Caneta metálica', quantidade: 500 },
  { category: 'Brindes - 2.5.2.8', month: 1, planejado: 6000.0, realizado: null, fornecedor: 'Junior Brindes', tituloCompra: 'Canetas plástica', quantidade: 3000 },
  { category: 'Brindes - 2.5.2.8', month: 2, planejado: null, realizado: 6000.0, fornecedor: 'Junior Brindes', tituloCompra: 'Canetas plástica', quantidade: 3000 },
  { category: 'Brindes - 2.5.2.8', month: 9, planejado: 6000.0, realizado: 6000.0, fornecedor: 'Junior Brindes', tituloCompra: 'Canetas plástica', quantidade: 3000 },
  { category: 'Brindes - 2.5.2.8', month: 5, planejado: 2700.0, realizado: null, fornecedor: '', tituloCompra: 'Chaveiro abridor', quantidade: 1000 },
  { category: 'Brindes - 2.5.2.8', month: 10, planejado: null, realizado: 2700.0, fornecedor: '', tituloCompra: 'Chaveiro abridor', quantidade: 1000 },
  { category: 'Brindes - 2.5.2.8', month: 11, planejado: 18000.0, realizado: 18000.0, fornecedor: '', tituloCompra: 'Copo Stanley', quantidade: 1000 },
  { category: 'Brindes - 2.5.2.8', month: 7, planejado: 4000.0, realizado: null, fornecedor: '', tituloCompra: 'Kit Faca (clientes especiais)', quantidade: 100 },
  { category: 'Brindes - 2.5.2.8', month: 10, planejado: null, realizado: 4000.0, fornecedor: '', tituloCompra: 'Kit Faca (clientes especiais)', quantidade: 100 },
  { category: 'Brindes - 2.5.2.8', month: 6, planejado: 2700.0, realizado: null, fornecedor: '', tituloCompra: 'Régua grande', quantidade: 300 },
  { category: 'Brindes - 2.5.2.8', month: 9, planejado: null, realizado: 2700.0, fornecedor: '', tituloCompra: 'Régua grande', quantidade: 300 },
  { category: 'Brindes - 2.5.2.8', month: 3, planejado: 9150.0, realizado: 9150.0, fornecedor: 'Gráfica XMais', tituloCompra: 'Sacolas Kraft', quantidade: 5000 },
  { category: 'Brindes - 2.5.2.8', month: 10, planejado: 9500.0, realizado: 9500.0, fornecedor: 'Gráfica XMais', tituloCompra: 'Sacolas Kraft', quantidade: 5000 },
  { category: 'Brindes - 2.5.2.8', month: 4, planejado: null, realizado: 3640.0, fornecedor: '', tituloCompra: 'Sal', quantidade: 400 },
  { category: 'Brindes - 2.5.2.8', month: 6, planejado: 9000.0, realizado: 9000.0, fornecedor: '', tituloCompra: 'Sal', quantidade: 400 },
  { category: 'PDV - 2.5.2.12', month: 4, planejado: null, realizado: 150.0, fornecedor: '', tituloCompra: 'Adesivo torneiras GhelPlus- SIG 2066', quantidade: null },
  { category: 'PDV - 2.5.2.12', month: 3, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes e balões consumidor final - Dia "G"', quantidade: 3000 },
  { category: 'PDV - 2.5.2.12', month: 7, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes e balões consumidor final - Dia "G"', quantidade: 3000 },
  { category: 'PDV - 2.5.2.12', month: 11, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes e balões consumidor final - Dia "G"', quantidade: 3000 },
  { category: 'PDV - 2.5.2.12', month: 4, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes vendedores/balconistas - cliente oculto', quantidade: 1000 },
  { category: 'PDV - 2.5.2.12', month: 6, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes vendedores/balconistas - cliente oculto', quantidade: 1000 },
  { category: 'PDV - 2.5.2.12', month: 8, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes vendedores/balconistas - cliente oculto', quantidade: 1000 },
  { category: 'PDV - 2.5.2.12', month: 10, planejado: 1500.0, realizado: null, fornecedor: '', tituloCompra: 'Brindes vendedores/balconistas - cliente oculto', quantidade: 1000 },
  { category: 'PDV - 2.5.2.12', month: 2, planejado: 3500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração "Faço parte do TimAÇO GhelPlus"', quantidade: '50 lojas' },
  { category: 'PDV - 2.5.2.12', month: 5, planejado: 3500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração "Faço parte do TimAÇO GhelPlus"', quantidade: '50 lojas' },
  { category: 'PDV - 2.5.2.12', month: 9, planejado: 3500.0, realizado: null, fornecedor: '', tituloCompra: 'Decoração "Faço parte do TimAÇO GhelPlus"', quantidade: '50 lojas' },
  { category: 'PDV - 2.5.2.12', month: 4, planejado: null, realizado: 200.0, fornecedor: '', tituloCompra: 'Logos representante (Flávi Bacana) SOLI 1688', quantidade: null },
  { category: 'PDV - 2.5.2.12', month: 7, planejado: null, realizado: 3600.0, fornecedor: '', tituloCompra: 'Materiais Copa - banner', quantidade: null },
  { category: 'PDV - 2.5.2.12', month: 7, planejado: null, realizado: 5090.0, fornecedor: '', tituloCompra: 'Materiais Copa - bola', quantidade: null },
  { category: 'PDV - 2.5.2.12', month: 5, planejado: null, realizado: 1300.0, fornecedor: '', tituloCompra: 'Placa Showroom- Flávio Barreto SIG 2228 - cliente Irmãos Queiroz', quantidade: null },
  { category: 'PDV - 2.5.2.12', month: 7, planejado: null, realizado: 490.0, fornecedor: '', tituloCompra: 'Placa Showroom- SIG 2465 - cliente Barkev- Pedro Cesar', quantidade: null },
  { category: 'PDV - 2.5.2.12', month: 4, planejado: null, realizado: 370.0, fornecedor: '', tituloCompra: 'PLacas de acrílico- SIG 2059', quantidade: 10 },
  { category: 'PDV - 2.5.2.12', month: 10, planejado: null, realizado: 5050.0, fornecedor: '', tituloCompra: 'Premiações em $ Campanha timAÇO', quantidade: 6 },
  { category: 'PDV - 2.5.2.12', month: 10, planejado: 25000.0, realizado: null, fornecedor: '', tituloCompra: 'Viagem 5 lojistas c/ acompanhante', quantidade: 10 },
  { category: 'PDV - 2.5.2.12', month: 3, planejado: 3000.0, realizado: null, fornecedor: '', tituloCompra: 'Álbum de figurinhas lojistas', quantidade: 50 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: null, realizado: 6750.0, fornecedor: '', tituloCompra: 'Acomac- caxias do sul', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 1, planejado: null, realizado: 35.0, fornecedor: '', tituloCompra: 'Amostra cordão feira', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: null, realizado: 195.75, fornecedor: '', tituloCompra: 'Assessoria extra feira Feicon', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: 25000.0, realizado: null, fornecedor: '', tituloCompra: 'Cachê Neto', quantidade: 1 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: null, realizado: 4000.0, fornecedor: '', tituloCompra: 'Conexão Atini (Evento Roni)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 5, planejado: null, realizado: 4000.0, fornecedor: '', tituloCompra: 'Conexão Atini (Evento Roni)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 6, planejado: null, realizado: 4000.0, fornecedor: '', tituloCompra: 'Conexão Atini (Evento Roni)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 8, planejado: null, realizado: 2500.0, fornecedor: '', tituloCompra: 'Conexão Atini (Evento Roni)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 9, planejado: null, realizado: 2500.0, fornecedor: '', tituloCompra: 'Conexão Atini (Evento Roni)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 2500.0, realizado: 2500.0, fornecedor: '', tituloCompra: 'Feicon - Coletor de Dados', quantidade: 1 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon - margem p/ emergências', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 400.0, realizado: 400.0, fornecedor: '', tituloCompra: 'Feicon - Placas de identificação', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 1, planejado: 99.0, realizado: 9008.05, fornecedor: '', tituloCompra: 'Feicon 2026 - Espaço', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 9008.05, realizado: 9008.05, fornecedor: '', tituloCompra: 'Feicon 2026 - Espaço', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 3, planejado: 9008.05, realizado: 9008.05, fornecedor: '', tituloCompra: 'Feicon 2026 - Espaço', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 1500.0, realizado: 1500.0, fornecedor: '', tituloCompra: 'Feicon 2026 - KVA', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 1, planejado: 20617.9, realizado: 20617.9, fornecedor: '', tituloCompra: 'Feicon 2026 - Montagem - Arq Eventos', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 20617.9, realizado: 20617.9, fornecedor: '', tituloCompra: 'Feicon 2026 - Montagem - Arq Eventos', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 3, planejado: 20617.9, realizado: 20617.9, fornecedor: '', tituloCompra: 'Feicon 2026 - Montagem - Arq Eventos', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: 20617.9, realizado: 20617.9, fornecedor: '', tituloCompra: 'Feicon 2026 - Montagem - Arq Eventos', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 5, planejado: null, realizado: 4172.43, fornecedor: '', tituloCompra: 'Feicon 2026 - Montagem - Arq Eventos Extras', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 5, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 6, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 7, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 8, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 9, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 10, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 11, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 12, planejado: 9500.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - locação', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 11, planejado: 22000.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - produção', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 12, planejado: 22000.0, realizado: null, fornecedor: '', tituloCompra: 'Feicon 2027 - produção', quantidade: '54m²' },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 15000.0, realizado: 15000.0, fornecedor: '', tituloCompra: 'Feicon Buffet', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 1400.0, realizado: 231.0, fornecedor: '', tituloCompra: 'Feicon Camisa Staff', quantidade: 7 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 4500.0, realizado: 3850.0, fornecedor: '', tituloCompra: 'Feicon Camisetas', quantidade: 69 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 420.0, realizado: 360.0, fornecedor: '', tituloCompra: 'Feicon Cordão', quantidade: 100 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Feicon Credenciais adicionais', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 300.0, realizado: 300.0, fornecedor: '', tituloCompra: 'Feicon Extintores', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 35000.0, realizado: 35000.0, fornecedor: '', tituloCompra: 'Feicon Hotel', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: 1200.0, realizado: 1200.0, fornecedor: '', tituloCompra: 'Feicon Taxa hidráulica', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 1, planejado: 3749.25, realizado: 3749.25, fornecedor: '', tituloCompra: 'Feicon vídeos- Inout', quantidade: 1 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: 3749.25, realizado: 3749.25, fornecedor: '', tituloCompra: 'Feicon vídeos- Inout', quantidade: 1 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 3, planejado: null, realizado: 2010.0, fornecedor: '', tituloCompra: 'Feicon- Bolas TimAço', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: null, realizado: 1000.0, fornecedor: 'WBS AUDIOVIS', tituloCompra: 'Feicon- locação microfone', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 3, planejado: null, realizado: 450.0, fornecedor: '', tituloCompra: 'Feicon- Suporte Bola', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 6, planejado: null, realizado: 2880.0, fornecedor: '', tituloCompra: 'Fenarem', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 7, planejado: null, realizado: 2880.0, fornecedor: '', tituloCompra: 'Fenarem', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 8, planejado: null, realizado: 2880.0, fornecedor: '', tituloCompra: 'Fenarem', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 9, planejado: null, realizado: 2880.0, fornecedor: '', tituloCompra: 'Fenarem', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: 15000.0, realizado: null, fornecedor: '', tituloCompra: 'Influencers', quantidade: 3 },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 3, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros / Rodada de Negócios', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 7, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros / Rodada de Negócios', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 10, planejado: 2000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros / Rodada de Negócios', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 9, planejado: null, realizado: 1000.0, fornecedor: '', tituloCompra: 'Rede Nova Max', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 2, planejado: null, realizado: 1000.0, fornecedor: '', tituloCompra: 'Salão do Imóvel (Chapecó- SC)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 3, planejado: null, realizado: 1000.0, fornecedor: '', tituloCompra: 'Salão do Imóvel (Chapecó- SC)', quantidade: null },
  { category: 'Feiras e Eventos - 2.5.2.22', month: 4, planejado: null, realizado: 1000.0, fornecedor: '', tituloCompra: 'Salão do Imóvel (Chapecó- SC)', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 5, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 6, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 7, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 8, planejado: 7000.0, realizado: null, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 9, planejado: 7000.0, realizado: 7000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 10, planejado: 7000.0, realizado: 7000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 11, planejado: 7000.0, realizado: 7000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 12, planejado: 7000.0, realizado: 7000.0, fornecedor: '', tituloCompra: 'Reformas', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 8, planejado: null, realizado: 2025.0, fornecedor: '', tituloCompra: 'Showroom - SP (materiais)', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 8, planejado: null, realizado: 1000.0, fornecedor: '', tituloCompra: 'Showroom- SP (serviços)', quantidade: null },
  { category: 'Showroom - 2.5.2.13', month: 9, planejado: null, realizado: 2000.0, fornecedor: '', tituloCompra: 'Showroom- SP (serviços)', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 3, planejado: null, realizado: 343.5, fornecedor: '', tituloCompra: 'Exp TQ Monobloco 30L- SIG 1949', quantidade: 5 },
  { category: 'Expositores Padrão - 2.5.2.14', month: 3, planejado: null, realizado: 2845.0, fornecedor: '', tituloCompra: 'Expositor TQ Monolobloco preto TX- SIG 1967', quantidade: 5 },
  { category: 'Expositores Padrão - 2.5.2.14', month: 4, planejado: null, realizado: 11290.5, fornecedor: '', tituloCompra: 'Expositores - SIG 2133', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 4, planejado: null, realizado: 4960.0, fornecedor: '', tituloCompra: 'Expositores - SIG 2137', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 5, planejado: null, realizado: 13080.0, fornecedor: '', tituloCompra: 'Expositores - SIG 2213', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 6, planejado: null, realizado: 32485.0, fornecedor: '', tituloCompra: 'Expositores - SIG 2285', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 6, planejado: null, realizado: 9950.0, fornecedor: '', tituloCompra: 'Expositores - SIG 2286', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 3, planejado: 80000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 5, planejado: 80000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 7, planejado: 80000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 8, planejado: 80000.0, realizado: null, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 9, planejado: 80000.0, realizado: 80000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 10, planejado: null, realizado: 80000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 11, planejado: 80000.0, realizado: 80000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 12, planejado: null, realizado: 80000.0, fornecedor: '', tituloCompra: 'Outros', quantidade: null },
  { category: 'Expositores Padrão - 2.5.2.14', month: 3, planejado: null, realizado: 687.0, fornecedor: '', tituloCompra: 'Tampos de expositores de tanque', quantidade: '10 UN' },
  { category: 'Expositores Especiais - 2.5.2.20', month: 5, planejado: 50000.0, realizado: null, fornecedor: '', tituloCompra: '(sem título)', quantidade: null },
  { category: 'Expositores Especiais - 2.5.2.20', month: 9, planejado: 50000.0, realizado: 50000.0, fornecedor: '', tituloCompra: '(sem título)', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 4, planejado: null, realizado: 353.0, fornecedor: '', tituloCompra: 'Adaptadores de computador - SIG 2047', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 3, planejado: null, realizado: 299.0, fornecedor: '', tituloCompra: 'Adesivo- correção canal- SIG 1982', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 3, planejado: null, realizado: 4719.6, fornecedor: '', tituloCompra: 'Ar condicionado- SIG 1947', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 1, planejado: 374.06, realizado: 374.06, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 2, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 3, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 4, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 5, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 6, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 7, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 8, planejado: 500.0, realizado: null, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 9, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 10, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 11, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 12, planejado: 500.0, realizado: 500.0, fornecedor: '', tituloCompra: 'Bobina papel sulfite p/ plotter 180g 610x25m', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 3, planejado: null, realizado: 153.0, fornecedor: '', tituloCompra: 'Fones de ouvido- SIG 1925', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 3, planejado: null, realizado: 1396.41, fornecedor: '', tituloCompra: 'Monitor- SIG 2003', quantidade: null },
  { category: 'Equipamentos - 1.2.5.1', month: 1, planejado: 387.0, realizado: 387.0, fornecedor: '', tituloCompra: 'Tanque De Manutenção De Tinta Epson - C13s210057', quantidade: null },
];

module.exports = { ENTRIES_2026_GHELPLUS_GRANULAR };
